---
title: "Startups 2025"
format: html
editor: visual
---

```{r}
#| echo: false

pacman::p_load(tidyverse, janitor)
```

## Supera

A base de dados consolidada em 2025 da Supera abrange 35 empresas, das quais 28 forneceram dados mensuráveis.

## Estágio de desenvolvimento

```{r}
#| echo: false
#| warning: false
#supera_2025 <- Supera_Parque |> 
#  select(1:12) |> 
#  clean_names()
supera_2025 <- read_csv("supera_2025.csv")
```

```{r}
#| echo: false

supera_2025$x12_estagio_de_desenvolvimento <- factor(
  supera_2025$x12_estagio_de_desenvolvimento,
  levels = c("Validação", "Tração", "Operação", "Escala")
)

library(dplyr)
library(ggplot2)

supera_2025 %>%
  filter(!is.na(x12_estagio_de_desenvolvimento)) %>%
  ggplot(aes(x = x12_estagio_de_desenvolvimento)) +
  geom_bar(fill = "#5d8aa8") +
  geom_text(
    stat = "count",
    aes(label = after_stat(count)),
    hjust = -0.1
  ) +
  coord_flip() +
  labs(
    title = "Estágio de Desenvolvimento das Startups (ordem TRL)",
    x = "Estágio (TRL)",
    y = "Quantidade"
  ) +
  theme_bw()


```

```{r}
#| echo: false

supera_2025 %>%
  filter(!is.na(x6_segmento), x6_segmento != "") %>%
  ggplot(aes(x = x6_segmento)) +
  geom_bar(fill = "#5d8aa8") +
  geom_text(
    stat = "count",
    aes(label = after_stat(count)),
    hjust = -0.1
  ) +
  coord_flip() +
  labs(
    title = "Distribuição das Startups por Segmento",
    x = "Segmento",
    y = "Quantidade"
  ) +
  theme_bw() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

```

Múltiplos segmentos em linhas diferentes.

```{r}
#| echo: false

supera_2025 %>%
  # filtra registros válidos
  filter(!is.na(x6_segmento), x6_segmento != "") %>%
  # separa múltiplos segmentos em linhas diferentes
  separate_rows(x6_segmento, sep = ",\\s*") %>%
  # remove espaços extras
  mutate(x6_segmento = trimws(x6_segmento)) %>%
  # conta frequência de cada segmento e transforma em factor ordenado
  count(x6_segmento, sort = TRUE) %>%
  mutate(x6_segmento = factor(x6_segmento, levels = rev(x6_segmento))) %>%
  # plota
  ggplot(aes(x = x6_segmento, y = n)) +
  geom_bar(stat = "identity", fill = "#5d8aa8") +
  geom_text(aes(label = n), hjust = -0.1) +
  coord_flip() +
  labs(
    title = "Distribuição das Startups por Segmento",
    x = "Segmento",
    y = "Quantidade"
  ) +
  theme_bw() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

```
